apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: springcicddemo
  namespace: default
spec:
  hosts:
  - "backend.ns.com"
  gateways:
  - backend-gateway
  http:
  - match:
    - headers:
        canary:
          exact: "canary-tester"
    route:
    - destination:
        host: springcicddemo.default.svc.cluster.local
        subset: v2
        port:
          number: 9090
      weight: 100
  - match:
    - {} 
    route:
    - destination:
        host: springcicddemo.default.svc.cluster.local
        port:
          number: 9090
        subset: v1  
      weight: 100
    - destination:
        host: springcicddemo.default.svc.cluster.local
        port:
          number: 9090
        subset: v2  
      weight: 0